/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__newline = 1,
  anon_sym_Rulefired_COLON = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  sym_builtin = 5,
  sym_module = 6,
  anon_sym_Inliningdone_COLON = 7,
  anon_sym_Simplifier = 8,
  aux_sym_iterations_token1 = 9,
  anon_sym_Totalticks_COLON = 10,
  sym_number = 11,
  sym_category_name = 12,
  sym__indent = 13,
  sym_rule_name = 14,
  sym_inlined_id = 15,
  sym_detail = 16,
  sym_source_file = 17,
  sym__entry = 18,
  sym_rule_firing = 19,
  sym_provenance = 20,
  sym_inlining = 21,
  sym_iterations = 22,
  sym_total_ticks = 23,
  sym_tick_category = 24,
  sym_tick_detail = 25,
  sym_detail_name = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_tick_category_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__newline] = "_newline",
  [anon_sym_Rulefired_COLON] = "Rule fired:",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_builtin] = "builtin",
  [sym_module] = "module",
  [anon_sym_Inliningdone_COLON] = "Inlining done:",
  [anon_sym_Simplifier] = "Simplifier",
  [aux_sym_iterations_token1] = "iterations_token1",
  [anon_sym_Totalticks_COLON] = "Total ticks:",
  [sym_number] = "number",
  [sym_category_name] = "category_name",
  [sym__indent] = "_indent",
  [sym_rule_name] = "rule_name",
  [sym_inlined_id] = "inlined_id",
  [sym_detail] = "detail",
  [sym_source_file] = "source_file",
  [sym__entry] = "_entry",
  [sym_rule_firing] = "rule_firing",
  [sym_provenance] = "provenance",
  [sym_inlining] = "inlining",
  [sym_iterations] = "iterations",
  [sym_total_ticks] = "total_ticks",
  [sym_tick_category] = "tick_category",
  [sym_tick_detail] = "tick_detail",
  [sym_detail_name] = "detail_name",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tick_category_repeat1] = "tick_category_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__newline] = sym__newline,
  [anon_sym_Rulefired_COLON] = anon_sym_Rulefired_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_builtin] = sym_builtin,
  [sym_module] = sym_module,
  [anon_sym_Inliningdone_COLON] = anon_sym_Inliningdone_COLON,
  [anon_sym_Simplifier] = anon_sym_Simplifier,
  [aux_sym_iterations_token1] = aux_sym_iterations_token1,
  [anon_sym_Totalticks_COLON] = anon_sym_Totalticks_COLON,
  [sym_number] = sym_number,
  [sym_category_name] = sym_category_name,
  [sym__indent] = sym__indent,
  [sym_rule_name] = sym_rule_name,
  [sym_inlined_id] = sym_inlined_id,
  [sym_detail] = sym_detail,
  [sym_source_file] = sym_source_file,
  [sym__entry] = sym__entry,
  [sym_rule_firing] = sym_rule_firing,
  [sym_provenance] = sym_provenance,
  [sym_inlining] = sym_inlining,
  [sym_iterations] = sym_iterations,
  [sym_total_ticks] = sym_total_ticks,
  [sym_tick_category] = sym_tick_category,
  [sym_tick_detail] = sym_tick_detail,
  [sym_detail_name] = sym_detail_name,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tick_category_repeat1] = aux_sym_tick_category_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_Rulefired_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_builtin] = {
    .visible = true,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Inliningdone_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Simplifier] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_iterations_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Totalticks_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_category_name] = {
    .visible = true,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym_rule_name] = {
    .visible = true,
    .named = true,
  },
  [sym_inlined_id] = {
    .visible = true,
    .named = true,
  },
  [sym_detail] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__entry] = {
    .visible = false,
    .named = true,
  },
  [sym_rule_firing] = {
    .visible = true,
    .named = true,
  },
  [sym_provenance] = {
    .visible = true,
    .named = true,
  },
  [sym_inlining] = {
    .visible = true,
    .named = true,
  },
  [sym_iterations] = {
    .visible = true,
    .named = true,
  },
  [sym_total_ticks] = {
    .visible = true,
    .named = true,
  },
  [sym_tick_category] = {
    .visible = true,
    .named = true,
  },
  [sym_tick_detail] = {
    .visible = true,
    .named = true,
  },
  [sym_detail_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tick_category_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_count = 1,
  field_detail = 2,
  field_name = 3,
  field_provenance = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_count] = "count",
  [field_detail] = "detail",
  [field_name] = "name",
  [field_provenance] = "provenance",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_detail, 1},
  [2] =
    {field_count, 1},
  [3] =
    {field_count, 0},
    {field_name, 1},
  [5] =
    {field_name, 1},
    {field_provenance, 2},
  [7] =
    {field_count, 1},
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        '\n', 59,
        '\r', 1,
        '(', 62,
        ')', 63,
        'B', 15,
        'I', 40,
        'R', 52,
        'S', 27,
        'T', 44,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(59);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(58);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(51);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(60);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(123);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(72);
      END_STATE();
    case 9:
      if (lookahead == 'B') ADVANCE(70);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(71);
      END_STATE();
    case 10:
      if (lookahead == 'I') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'I') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'L') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'N') ADVANCE(64);
      END_STATE();
    case 14:
      if (lookahead == 'T') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'U') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(37);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(6);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(45);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(3);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(28);
      END_STATE();
    case 25:
      if (lookahead == 'f') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 'g') ADVANCE(4);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 33:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 34:
      if (lookahead == 'k') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 39:
      if (lookahead == 'm') ADVANCE(46);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 45:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 46:
      if (lookahead == 'p') ADVANCE(38);
      END_STATE();
    case 47:
      if (lookahead == 'r') ADVANCE(74);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 49:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 53:
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\f' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 54:
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(54);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(126);
      END_STATE();
    case 55:
      if (eof) ADVANCE(57);
      if (lookahead == '\n') ADVANCE(58);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '(') ADVANCE(62);
      if (lookahead == 'I') ADVANCE(40);
      if (lookahead == 'R') ADVANCE(52);
      if (lookahead == 'S') ADVANCE(27);
      if (lookahead == 'T') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 56:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        '\n', 58,
        '\r', 2,
        'I', 107,
        'R', 119,
        'S', 94,
        'T', 111,
        '\t', 82,
        '\f', 82,
        ' ', 82,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (lookahead != 0) ADVANCE(122);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(127);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_Rulefired_COLON);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_Rulefired_COLON);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_builtin);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_module);
      if (lookahead == 'I') ADVANCE(67);
      if (lookahead == '\'' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_module);
      if (lookahead == 'I') ADVANCE(68);
      if (lookahead == '\'' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_module);
      if (lookahead == 'L') ADVANCE(69);
      if (lookahead == '\'' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_module);
      if (lookahead == 'N') ADVANCE(64);
      if (lookahead == '\'' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_module);
      if (lookahead == 'T') ADVANCE(66);
      if (lookahead == '\'' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_module);
      if (lookahead == 'U') ADVANCE(65);
      if (lookahead == '\'' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_module);
      if (lookahead == '\'' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_Inliningdone_COLON);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_Inliningdone_COLON);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_Simplifier);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_Simplifier);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == ' ') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == ' ') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == ':') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == ':') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == ':') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'I') ADVANCE(107);
      if (lookahead == 'R') ADVANCE(119);
      if (lookahead == 'S') ADVANCE(94);
      if (lookahead == 'T') ADVANCE(111);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\f' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'a') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'c') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'd') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'd') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'e') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'e') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'e') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'e') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'f') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'f') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'g') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'i') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'i') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'i') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'i') ADVANCE(109);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'i') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'i') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'i') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'k') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'l') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'l') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'l') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'l') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'm') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'n') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'n') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'n') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'n') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'o') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'o') ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'p') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'r') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'r') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 's') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 't') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 't') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == 'u') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\f' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_iterations_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_Totalticks_COLON);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_Totalticks_COLON);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(122);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_category_name);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym__indent);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(127);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 55},
  [2] = {.lex_state = 55},
  [3] = {.lex_state = 55},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 55},
  [10] = {.lex_state = 56},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 55},
  [14] = {.lex_state = 55},
  [15] = {.lex_state = 55},
  [16] = {.lex_state = 55},
  [17] = {.lex_state = 55},
  [18] = {.lex_state = 55},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 53},
  [22] = {.lex_state = 0, .external_lex_state = 3},
  [23] = {.lex_state = 54},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_Rulefired_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_builtin] = ACTIONS(1),
    [anon_sym_Inliningdone_COLON] = ACTIONS(1),
    [anon_sym_Simplifier] = ACTIONS(1),
    [anon_sym_Totalticks_COLON] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym_rule_name] = ACTIONS(1),
    [sym_inlined_id] = ACTIONS(1),
    [sym_detail] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(24),
    [sym__entry] = STATE(2),
    [sym_rule_firing] = STATE(2),
    [sym_inlining] = STATE(2),
    [sym_iterations] = STATE(2),
    [sym_total_ticks] = STATE(2),
    [sym_tick_category] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [anon_sym_Rulefired_COLON] = ACTIONS(7),
    [anon_sym_Inliningdone_COLON] = ACTIONS(9),
    [anon_sym_Simplifier] = ACTIONS(11),
    [anon_sym_Totalticks_COLON] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(7), 1,
      anon_sym_Rulefired_COLON,
    ACTIONS(9), 1,
      anon_sym_Inliningdone_COLON,
    ACTIONS(11), 1,
      anon_sym_Simplifier,
    ACTIONS(13), 1,
      anon_sym_Totalticks_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym__newline,
    STATE(3), 7,
      sym__entry,
      sym_rule_firing,
      sym_inlining,
      sym_iterations,
      sym_total_ticks,
      sym_tick_category,
      aux_sym_source_file_repeat1,
  [31] = 8,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym__newline,
    ACTIONS(26), 1,
      anon_sym_Rulefired_COLON,
    ACTIONS(29), 1,
      anon_sym_Inliningdone_COLON,
    ACTIONS(32), 1,
      anon_sym_Simplifier,
    ACTIONS(35), 1,
      anon_sym_Totalticks_COLON,
    ACTIONS(38), 1,
      sym_number,
    STATE(3), 7,
      sym__entry,
      sym_rule_firing,
      sym_inlining,
      sym_iterations,
      sym_total_ticks,
      sym_tick_category,
      aux_sym_source_file_repeat1,
  [62] = 5,
    ACTIONS(43), 1,
      sym__newline,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(48), 1,
      sym__indent,
    STATE(6), 2,
      sym_tick_detail,
      aux_sym_tick_category_repeat1,
    ACTIONS(41), 5,
      ts_builtin_sym_end,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
  [83] = 4,
    ACTIONS(52), 1,
      sym__newline,
    ACTIONS(54), 1,
      sym__indent,
    STATE(5), 2,
      sym_tick_detail,
      aux_sym_tick_category_repeat1,
    ACTIONS(50), 6,
      ts_builtin_sym_end,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
  [102] = 4,
    ACTIONS(48), 1,
      sym__indent,
    ACTIONS(59), 1,
      sym__newline,
    STATE(5), 2,
      sym_tick_detail,
      aux_sym_tick_category_repeat1,
    ACTIONS(57), 6,
      ts_builtin_sym_end,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
  [121] = 4,
    ACTIONS(48), 1,
      sym__indent,
    ACTIONS(59), 1,
      sym__newline,
    STATE(8), 2,
      sym_tick_detail,
      aux_sym_tick_category_repeat1,
    ACTIONS(57), 6,
      ts_builtin_sym_end,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
  [140] = 4,
    ACTIONS(48), 1,
      sym__indent,
    ACTIONS(63), 1,
      sym__newline,
    STATE(5), 2,
      sym_tick_detail,
      aux_sym_tick_category_repeat1,
    ACTIONS(61), 6,
      ts_builtin_sym_end,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
  [159] = 3,
    ACTIONS(67), 1,
      anon_sym_LPAREN,
    STATE(17), 1,
      sym_provenance,
    ACTIONS(65), 7,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
  [175] = 3,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      aux_sym_iterations_token1,
    ACTIONS(71), 6,
      sym__newline,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
  [190] = 2,
    ACTIONS(77), 1,
      sym__newline,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
      sym__indent,
  [203] = 2,
    ACTIONS(81), 1,
      sym__newline,
    ACTIONS(79), 7,
      ts_builtin_sym_end,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
      sym__indent,
  [216] = 1,
    ACTIONS(83), 7,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
  [226] = 1,
    ACTIONS(85), 7,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
  [236] = 1,
    ACTIONS(87), 7,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
  [246] = 1,
    ACTIONS(89), 7,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
  [256] = 1,
    ACTIONS(91), 7,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
  [266] = 1,
    ACTIONS(93), 7,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_Rulefired_COLON,
      anon_sym_Inliningdone_COLON,
      anon_sym_Simplifier,
      anon_sym_Totalticks_COLON,
      sym_number,
  [276] = 2,
    ACTIONS(95), 1,
      sym_inlined_id,
    ACTIONS(97), 1,
      sym_detail,
  [283] = 2,
    ACTIONS(99), 1,
      sym_builtin,
    ACTIONS(101), 1,
      sym_module,
  [290] = 2,
    ACTIONS(103), 1,
      aux_sym_iterations_token1,
    STATE(12), 1,
      sym_detail_name,
  [297] = 1,
    ACTIONS(105), 1,
      sym_rule_name,
  [301] = 1,
    ACTIONS(107), 1,
      sym_category_name,
  [305] = 1,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
  [309] = 1,
    ACTIONS(111), 1,
      sym_number,
  [313] = 1,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
  [317] = 1,
    ACTIONS(115), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 83,
  [SMALL_STATE(6)] = 102,
  [SMALL_STATE(7)] = 121,
  [SMALL_STATE(8)] = 140,
  [SMALL_STATE(9)] = 159,
  [SMALL_STATE(10)] = 175,
  [SMALL_STATE(11)] = 190,
  [SMALL_STATE(12)] = 203,
  [SMALL_STATE(13)] = 216,
  [SMALL_STATE(14)] = 226,
  [SMALL_STATE(15)] = 236,
  [SMALL_STATE(16)] = 246,
  [SMALL_STATE(17)] = 256,
  [SMALL_STATE(18)] = 266,
  [SMALL_STATE(19)] = 276,
  [SMALL_STATE(20)] = 283,
  [SMALL_STATE(21)] = 290,
  [SMALL_STATE(22)] = 297,
  [SMALL_STATE(23)] = 301,
  [SMALL_STATE(24)] = 305,
  [SMALL_STATE(25)] = 309,
  [SMALL_STATE(26)] = 313,
  [SMALL_STATE(27)] = 317,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tick_category, 2, 0, 4),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tick_category, 2, 0, 4),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_tick_category, 2, 0, 4), SHIFT(7),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tick_category_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tick_category_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tick_category_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tick_category, 3, 0, 4),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tick_category, 3, 0, 4),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tick_category, 4, 0, 4),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tick_category, 4, 0, 4),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_firing, 2, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iterations, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_iterations, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_detail_name, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_detail_name, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tick_detail, 3, 0, 6),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tick_detail, 3, 0, 6),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inlining, 2, 0, 2),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iterations, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inlining, 2, 0, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_total_ticks, 2, 0, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_firing, 3, 0, 5),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_provenance, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [109] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_rule_name = 0,
  ts_external_token_inlined_id = 1,
  ts_external_token_detail = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_rule_name] = sym_rule_name,
  [ts_external_token_inlined_id] = sym_inlined_id,
  [ts_external_token_detail] = sym_detail,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_rule_name] = true,
    [ts_external_token_inlined_id] = true,
    [ts_external_token_detail] = true,
  },
  [2] = {
    [ts_external_token_inlined_id] = true,
    [ts_external_token_detail] = true,
  },
  [3] = {
    [ts_external_token_rule_name] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_ghc_core_explain_external_scanner_create(void);
void tree_sitter_ghc_core_explain_external_scanner_destroy(void *);
bool tree_sitter_ghc_core_explain_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_ghc_core_explain_external_scanner_serialize(void *, char *);
void tree_sitter_ghc_core_explain_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ghc_core_explain(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_ghc_core_explain_external_scanner_create,
      tree_sitter_ghc_core_explain_external_scanner_destroy,
      tree_sitter_ghc_core_explain_external_scanner_scan,
      tree_sitter_ghc_core_explain_external_scanner_serialize,
      tree_sitter_ghc_core_explain_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "ghc_core_explain",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
